### ISSUE TITLE
Не желаете закоммитить в Qt?

### ISSUE THREAD

**Issue by seniorivn** [SiberianProgrammers/sp_qt_libs#1]
посмотрел ваш код(я недавно решил использовать Qt для мобильной разработки) казалось бы всё это должно быть в составе фреймворка(в идеале). Есть причины держать это отдельно(кроме 'неготово')?

**Comment by aleus** [comment]
Нет. Во-первых, в Qt есть свой план разработки нового функционала и компонентов и наши наработки в него не входят. Следовательно мы не сможем закомитить в Qt. Во-вторых, всё-таки наш код представляет собой самостоятельную надстройку для разработки мобильных приложений, наподобии v-play.net.
